name: "Deploy GitHub Pages"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Perform Checkout
        uses: actions/checkout@v3

      - name: Insert Git Hash
        run: git rev-parse --short HEAD | awk '{printf("export const HASH = \"%s\"", $0)}' >> src/gitinfo.ts

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages